# TODO: CREATE CLASS 
# TODO: ADD SET OF QUESTIONS AND ANSWERS (USE DICTIONARY)
# TODO: ADD METHOD TO ASK QUESTIONS AND GET USER INPUT
# TODO: ADD METHOD TO CHECK ANSWERS AND CALCULATE SCORE
# TODO: ADD METHOD TO DISPLAY FINAL SCORE
# TODO: ADD METHOD TO RESTART QUIZ
# TODO: ADD METHOD TO EXIT QUIZ
