# TODO: CREATE CLASS 
# TODO: ADD SET OF QUESTIONS AND ANSWERS (USE DICTIONARY) (GROUP IT INTO TOPICS) (USER SELECTS TOPICS)
# TODO: ADD METHOD TO ASK QUESTIONS AND GET USER INPUT
# TODO: ADD METHOD TO CHECK ANSWERS AND CALCULATE SCORE
# TODO: ADD METHOD TO DISPLAY FINAL SCORE
# TODO: ADD METHOD TO RESTART QUIZ
# TODO: ADD METHOD TO EXIT QUIZ

class Quiz:
    def __init__(self):
        self.questions = {
            "Math": {
                "What is 2 + 2?": "4",
                "What is 5 * 6?": "30"
            },
        }